#!/usr/bin/env python3
import argparse
import csv
import hashlib
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import torch

from training.registry import ROOT, model_spec, resolve_models


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def tensor_maps(value, prefix=""):
    if not isinstance(value, dict): return []
    found = []
    if any(torch.is_tensor(v) for v in value.values()): found.append((prefix or "root", value))
    for key, child in value.items():
        if isinstance(child, dict): found.extend(tensor_maps(child, f"{prefix}.{key}".strip(".")))
    return found


def inspect_torch(path):
    try:
        payload = torch.load(path, map_location="cpu", weights_only=True, mmap=True)
    except RuntimeError as exc:
        if "mmap can only" in str(exc): payload = torch.load(path, map_location="cpu", weights_only=True)
        else: raise
    maps = tensor_maps(payload)
    headlike = []
    for root, state in maps:
        for key, value in state.items():
            if torch.is_tensor(value) and value.ndim in (1, 2) and 400 in value.shape:
                headlike.append(f"{root}:{key}={tuple(value.shape)}")
    return type(payload).__name__, "; ".join(headlike[-12:])


def inspect(path):
    if path.suffix == ".safetensors":
        from safetensors import safe_open
        with safe_open(path, framework="pt", device="cpu") as handle:
            heads = [f"{key}={tuple(handle.get_slice(key).get_shape())}" for key in handle.keys() if 400 in handle.get_slice(key).get_shape()]
        return "safetensors", "; ".join(heads[-12:])
    return inspect_torch(path)


def audit(key):
    spec = model_spec(key); rel = spec.get("k400_checkpoint")
    path = ROOT / rel if rel else None
    row = {"model": key, "display_name": spec["display_name"], "file": rel or "", "exists": bool(path and path.is_file()), "opens": False, "structure": "", "head_evidence": "", "classes": "", "source": spec.get("checkpoint_origin", ""), "source_repo": spec["source_repo"], "source_commit": spec.get("source_commit") or "", "sha256": "", "status": spec["checkpoint_status"], "reason": ""}
    if not row["exists"]:
        if not row["status"].startswith("BLOCKED_EXACT") and row["status"] != "MISSING_EXACT_CHECKPOINT": row["status"] = "MISSING_EXACT_CHECKPOINT"
        row["reason"] = "exact configured file is absent"
        return row
    row["sha256"] = sha256(path)
    expected = spec.get("checkpoint_sha256")
    if expected and expected != row["sha256"]:
        row["status"] = "WRONG_ARCHITECTURE"; row["reason"] = "SHA256 differs from frozen manifest"; return row
    try:
        row["structure"], row["head_evidence"] = inspect(path); row["opens"] = True
    except Exception as exc:
        row["reason"] = f"safe open/config validation required: {type(exc).__name__}: {exc}"
        if row["status"] == "READY_EXACT": row["status"] = "READY_NEEDS_CONFIG_VALIDATION"
        return row
    row["classes"] = 400 if "400" in row["head_evidence"] else "unknown"
    if row["classes"] != 400:
        row["status"] = "WRONG_HEAD"; row["reason"] = "no safely observable 400-class head"
    elif row["status"] == "READY_NEEDS_CONFIG_VALIDATION":
        row["reason"] = "file/head valid; exact upstream config linkage still requires backend preflight"
    return row


def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--models", nargs="+", default=["frozen17"]); args=parser.parse_args()
    selected = resolve_models("frozen17" if args.models == ["frozen17"] else args.models)
    rows=[audit(key) for key in selected]
    reports=ROOT/"reports"; reports.mkdir(exist_ok=True)
    csv_path=reports/"checkpoint_audit.csv"
    with csv_path.open("w",newline="",encoding="utf-8") as h:
        w=csv.DictWriter(h,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    ready=sum(r["status"]=="READY_EXACT" for r in rows)
    lines=["# Frozen-17 checkpoint audit","",f"Generated by `scripts/audit_checkpoints.py`. Exact-ready: **{ready}/{len(rows)}**.","","| Model | File | SHA256 | Head | Status | Reason |","|---|---|---|---|---|---|"]
    for r in rows: lines.append(f"| {r['model']} | `{r['file'] or 'none'}` | `{r['sha256'] or 'n/a'}` | {r['classes']} | **{r['status']}** | {r['reason']} |")
    lines += ["", "`READY_NEEDS_CONFIG_VALIDATION` is intentionally not equivalent to `READY_EXACT`. MViTv2 artifacts and released SSV2 heads are never accepted as K400 starting checkpoints."]
    focal = [model_spec(key) for key in (
        "video-focalnet-t", "video-focalnet-s", "video-focalnet-b"
    )]
    lines += [
        "",
        "## Video-FocalNet parameter audit",
        "",
        "The frozen Stage-1 literature values remain **28M / 49M / 88M**; "
        "they are not overwritten. The exact executable T/S/B video graphs "
        "contain **49.553272M / 88.735168M / 157.389216M** parameters.",
        "",
        "Those runtime counts are calculated as `sum(tensor.numel())` across "
        "the complete strictly loaded official model state, including each "
        "400-way classification head. The checkpoint head shapes are visible "
        "in the table above. The additional parameters belong to the temporal "
        "modulation branches in the video model; the smaller historical "
        "figures correspond to the spatial image FocalNet backbone convention.",
        "",
        "Execution remains exact because the official Video-FocalNet "
        "constructors (official depths/dimensions) accept every official "
        "checkpoint with `strict=True`, and runtime preflight asserts the "
        "complete graph count within 5%. Historical Stage-1 selection metadata "
        "and executable runtime counts are emitted as separate fields.",
    ]
    (reports/"CHECKPOINT_AUDIT.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
    for r in rows: print(f"{r['model']}: {r['status']}")
    print(f"READY_EXACT={ready} BLOCKED_OR_OTHER={len(rows)-ready}")

if __name__ == "__main__": main()
